[application]
name = "peilbeheer-hhvr"

[web.app]
title = "Peilbeheer HHVR"

[web.resource.dev]
style = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
    "main.css",
]
script = [
    "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
    "https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js",
]
